// This file is autogenerated by Golem
// Do NOT make modifications, they will be lost
package nzbs

import (
	"github.com/gin-gonic/gin"

	"github.com/dashotv/golem/web"
	"github.com/dashotv/test/server"
)

type context struct {
	Server *server.Server
}

var local = &context{}

func Routes(s *server.Server) {
	local.Server = s
	r := s.Router.Group("/nzbs")
	r.Get("/add", addHandler)
	r.Get("/destroy", destroyHandler)
	r.Get("/history", historyHandler)
	r.Get("/", indexHandler)
	r.Get("/pause", pauseHandler)
	r.Get("/remove", removeHandler)
	r.Get("/resume", resumeHandler)

}

func addHandler(c *gin.Context) {
	url := web.QueryString(c, "url")
	category := web.QueryString(c, "category")
	name := web.QueryString(c, "name")

	add(url, category, name)
}

func destroyHandler(c *gin.Context) {
	id := web.QueryInt(c, "id")

	destroy(id)
}

func historyHandler(c *gin.Context) {
	hidden := web.QueryBool(c, "hidden")

	history(hidden)
}

func indexHandler(c *gin.Context) {

	index()
}

func pauseHandler(c *gin.Context) {
	id := web.QueryInt(c, "id")

	pause(id)
}

func removeHandler(c *gin.Context) {
	id := web.QueryInt(c, "id")

	remove(id)
}

func resumeHandler(c *gin.Context) {
	id := web.QueryInt(c, "id")

	resume(id)
}
